name: Production Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to EC2
              uses: appleboy/scp-action@v0.1.7 # This is the latest stable scp
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USER }}
                key: ${{ secrets.EC2_SSH_KEY_ED255_A }}
                source: "."
                target: "/home/ubuntu/whatsapp-bot"

            - name: Deploy with Docker Compose
              uses: appleboy/ssh-action@v1.2.0 # Updated from v1.0.3
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USER }}
                key: ${{ secrets.EC2_SSH_KEY_ED255_A }}
          script: |
            cd /home/ubuntu/whatsapp-bot

            echo "FASTAPI_URL=${{ secrets.FASTAPI_URL }}" > .env
            echo "VERIFY_TOKEN=${{ secrets.VERIFY_TOKEN }}" >> .env
            echo "KAFKA_BROKER=kafka:9092" >> .env

            sudo docker compose up -d --build
